### ISSUE TITLE
[team] Game Engine

### ISSUE THREAD

**Issue by eeeesong** [SinsaStation/FullStackCodingBot#10]
- 게임엔진 학습하기
- SpriteKit 학습하기
- 강의 구매시 공유

**Comment by eeeesong** [comment]
https://www.google.co.kr/amp/s/www.freecodecamp.org/news/spritekit-advanced-how-to-build-a-2-5d-game-part-i-2dc76c7c65e2/amp/

예시로 나오는 상어 게임이 우리가 만드려는 로직이랑 비슷하게 생김 
글은 아직 다 못읽었음

**Comment by torch-ray** [comment]
https://www.youtube.com/watch?v=1H9EG15mycI

spritekit 쓰면 만들 수 있을거 같은데? 여기서 사용한 중력효과 사용하면 언어로고 터질때마다 밑으로 자동으로 당겨질듯?
spritekit을 얼마나 잘 쓸 수 있을지가 관건인가? 안쓰고 구현하려면 절대 못하는 건가? 사실 이것도 좀 애매한듯...?

**Comment by eeeesong** [comment]
SpriteKit 쓰면 우리가 하려는 수준이면 뭐든 무조건 되긴 할텐데
우리가 그 Kit을 얼마나 쓸지 정도를 정하는 게 중요할 것 같긴 함..
보니까 이거 제대로 파려면 또 한세월 걸릴 것 같음ㅎㅎㅎ

**Comment by eeeesong** [comment]
좀 찾아보다보니까 그 부분에서 물리엔진 같은게 필요한게 아니라 
사실상 배열 등에 담긴 언어로고들을 2.5D 느낌으로 보여주기만 하면 되는거라
CALayer zPosition 바꾸는 로직 + zPosition에 따라 레이어 크기 조정하는 로직을 만드는 게 가볍고 빠를 수도 있을 것 같네요
[iCarousel](https://github.com/nicklockwood/iCarousel) <- 이 라이브러리에 있는 timeMachine 효과?를 활용하면 될듯!
[스택오버플로 질문 - uiview 시점 적용하기](https://stackoverflow.com/questions/347721/how-do-i-apply-a-perspective-transform-to-a-uiview) <- 집중이 안돼서 코드를 읽어보진 못했는데 이 질문이 딱 우리가 원하는 방법에 대한 질문 같음 (아침에 지하철에서 읽어볼 예정..)
