### ISSUE TITLE
Asset

### ISSUE THREAD

**Issue by eeeesong** [SinsaStation/FullStackCodingBot#11]
- 스토리 및 타이틀에 사용할 에셋 리스트 정하기

**Comment by torch-ray** [comment]
[pixel human](https://assetstore.unity.com/?q=pixel%20human&orderBy=1)
이렇게 검색하면 나오는거 이거 애니메이션 지원하면 우리 앱만들때도 그대로 사용할 수 있는건가?

**Comment by eeeesong** [comment]
음 보니까 그 unity 버전에 atlas 뭐 이런 말이 있는데
이 [sprite kit 애니메이션 튜토리얼](https://www.raywenderlich.com/144-spritekit-animations-and-texture-atlases-in-swift) 에서도 atlas를 지원하는 걸로 봐서는 호환시킬 수 있을 것 같은데요?
게다가 에셋 사면 PSD도 준다고 하니깐 바로 안되더라도 프레임마다 이미지 뽑아서 반복시키면 될듯

**Comment by eeeesong** [comment]
버튼 톤도 픽셀로 맞춰야 어울릴 것 같네요
[10달러짜리 고퀄리티](https://assetstore.unity.com/packages/2d/gui/icons/pixel-gui-46759)
[무료의 저퀄리티](https://assetstore.unity.com/packages/2d/gui/simple-retro-pixelart-gui-skin-50780)
[5달러짜리 괜춘퀄리티](https://assetstore.unity.com/packages/2d/gui/ngarden-retro-stone-ui-gray-145421)

**Comment by eeeesong** [comment]
쭉 봤는데 오피스 관련된 에셋이 그리 많지 않네요
위에도 올려주신 [pixel human 검색하면 바로 나오는거](https://assetstore.unity.com/packages/2d/characters/36-animated-pixel-humans-150852)
[롱다리 버전](https://assetstore.unity.com/packages/2d/characters/100-characters-pixel-art-pack-76854)
이렇게 두개가 그나마 쓸만한듯...

**Comment by eeeesong** [comment]
자체 제작으로 진행
