### ISSUE TITLE
게임 데이터 삭제되는 문제 

### ISSUE THREAD

**Issue by eeeesong** [SinsaStation/FullStackCodingBot#116]
<img width="1099" alt="스크린샷 2021-08-01 오후 10 15 17" src="https://user-images.githubusercontent.com/72188416/127772240-0d1439c4-bfad-44c4-b61d-095a456fa6c7.png">

- 성공적으로 로그인 정보를 불러 왔고, 이미 저장한 이력이 있는 아이디인데도 위의 타이밍에서 앱이 죽는 문제 발생

<img width="1125" alt="스크린샷 2021-08-01 오후 10 13 30" src="https://user-images.githubusercontent.com/72188416/127772174-ffc86786-cd99-4198-8b72-2801a7078dd3.png">

- 확인해보니 PersistenceStorage에서 생성되는 부분의 정보가 0으로 리셋되어 있음
- 어떤 포인트에서 삭제가 된 건지 파악 필요 -> 추측하는 건 게임 오버 시 저장이 다 끝나기 전에 앱이 종료 되어서 그런 것 같음..

**Comment by torch-ray** [comment]
transformToLocalData 파싱 실패시 빈배열 return하도록 에러처리해놨는데 이부분 손봐야할듯 합니다... 하... 언제 실패했는지를 모르겠네요

**Comment by torch-ray** [comment]
DataFormatManager 객체가 가지고 있는 메서드입니다.
