### ISSUE TITLE
SettingScene

### ISSUE THREAD

**Issue by torch-ray** [SinsaStation/FullStackCodingBot#118]
- SettingVC
- UserDefaults

**Comment by eeeesong** [comment]
빈곳 누르면 setting dismiss되는 기능을 요청드리고 싶습니다
자꾸 습관처럼 아래 공간을 눌러서 세팅 창을 닫으려고 하네요..

**Comment by eeeesong** [comment]
![button_setting](https://user-images.githubusercontent.com/72188416/128367437-9ad43412-5e2c-45f1-8479-ca15f12b90ce.png)

**Comment by eeeesong** [comment]
- 메뉴 카드 외 빈공간 터치 시 dismiss
