### ISSUE TITLE
[seok] ViewController 흐름도

### ISSUE THREAD

**Issue by eeeesong** [SinsaStation/FullStackCodingBot#12]
- 뷰컨트롤러 흐름도 그리기

**Comment by torch-ray** [comment]
![FullStackCodingBOt 001](https://user-images.githubusercontent.com/74946802/123540473-27e17100-d77a-11eb-9f7a-b05c5718fa44.jpeg)

**Comment by torch-ray** [comment]
광고제거 뷰컨트롤러 및 기타 뷰컨트롤러 내용은 우리 방식에 맞게 수정이 필요하고 // 또는 필요없을 수도 있음
