### ISSUE TITLE
Apple Game Center

### ISSUE THREAD

**Issue by torch-ray** [SinsaStation/FullStackCodingBot#13]
- 로그인 기능 대체해서 Apple Game Center 연동 구현

**Comment by eeeesong** [comment]
### 애플 공식 문서
[Game Kit 공식 문서](https://developer.apple.com/documentation/gamekit/)
[Game Center 개요](https://help.apple.com/app-store-connect/#/devb42a686f5)
- [신규 앱 추가하기](https://help.apple.com/app-store-connect/#/dev2cd126805)
> 필요 역할 : 계정 소유자, 앱 관리 또는 관리자. 역할 권한을 확인하십시오.
- 현재 코쿼계정에선 `제품 개발` 권한만 있음

**Comment by eeeesong** [comment]
[raywenderlich 튜토리얼](https://www.raywenderlich.com/7544-game-center-for-ios-building-a-turn-based-game)
[게임센터 LeaderBoards 튜토리얼](https://code.tutsplus.com/tutorials/game-center-and-leaderboards-for-your-ios-app--cms-27488)

**Comment by torch-ray** [comment]
[게임센터 파베랑 연결하기](https://hub1234.tistory.com/44?category=376918)
