### ISSUE TITLE
Game Story

### ISSUE THREAD

**Issue by torch-ray** [SinsaStation/FullStackCodingBot#131]
# FullStack Coding Master Story

## 설정
- ‘좋소 테크롤로지’, ‘버그 네트웍스’, ‘노예 이노베이션’
- 사장 & 개발자(1명) 2인 기업 or 가족기업(가족들 임원) & 개발자(1명)  4~5인 기업
- 사장(버그), 개발자(디버그)

## 스토리 No.1

- 버그: “디버그, 디버그 어딨나!?”
- 디버그: “네, 사장님”
- 버그: “(기획서를 건네며) API, DB설계하고, 웹사이트랑, 모바일 앱까지 만들면 돼”
- 디버그: “모바일은 iOS만요?”
- 버그: “당연히 안드로이드까지 만들어야지!?”
- 디버그: “…언제까지요?”
- 버그: “두달이면 충분하지 않겠나? 얼른 시작하게”
- 디버그: “…아아악!!!!”
> 분노의 코딩시작(게임스타트)

## 스토리 No.2

- bug: “(기획서를 건네며) 2달안에 제작해야하는 프로젝트니까 얼른 시작들 해봐”
- null(버그 와이프): “자, 2달이면 촉박하니까 얼른 모여서 시작해보세요. 저는 바빠서…”
- Debug: “저… 그럼 error님이 백엔드…”
- error(bug 아들): “아, 배고프네 점심이나 먹으러가지”
- failure(bug 딸): “네 ~ debug님 수고해요~”
- Debug: “…아아악!!!!”
> 분노의 코딩시작(게임스타트)

## 스토리 No.3
- debug: 프로젝트 마무리 됐습니다.
- Bug: (검토…) 여기 수정하게, 여기도, 여기도, 여기도 …
- Debug: 저 사장님, 모바일, 프론트 개발자들이 퇴사해서 이 부분은 제가 수정하기 어려울 거 같습니다.
- Bug: 무슨 소리야? 자네도 개발자 아닌가? 사람 곧 뽑아 줄테니 어서 시작하게
- Debug: …
- Bug: 뭐하고 있나? 어서 나가서 시작하게
- Debug: !!!!!!!(분노)
> 게임스타트

**Comment by torch-ray** [comment]
@eeeesong 의견좀요 ㅋㅋㅋㅋ

**Comment by eeeesong** [comment]
3번ㅋㅋㅋㅋㅋ3번 너무 좋네요

**Comment by eeeesong** [comment]
- [x] 스토리 다시보기 버튼
- [x] 스토리 넘기기 버튼

**Comment by eeeesong** [comment]
- 폰트 적용
