### ISSUE TITLE
How to play

### ISSUE THREAD

**Issue by eeeesong** [SinsaStation/FullStackCodingBot#141]
## How To Play
- 주어진 개발언어에 맞게 왼쪽/오른쪽 버튼을 누르면 됩니다.
- 올바른 버튼을 누르면 스코어가 상승합니다.
- 잘못된 버튼을 누르면 제한시간이 감소합니다.
- 피버모드에 진입시 타이머가 멈추며, 틀려도 시간이 감소하지 않습니다.

**Comment by torch-ray** [comment]
아이템 레벨업시 얻는 점수 상승

**Comment by eeeesong** [comment]
![button_howto](https://user-images.githubusercontent.com/72188416/128970235-06ea7d68-99a2-40e5-bb0e-2b560116994a.png)

@torch-ray  버튼 에셋 드립니다~

**Comment by eeeesong** [comment]
- 이미지 에셋 교체
- 설명 좌우 간격 조정
