### ISSUE TITLE
게임 진행 중 + 종료 메시지 업데이트 

### ISSUE THREAD

**Issue by torch-ray** [SinsaStation/FullStackCodingBot#153]
### 게임 중 - Unit Match 시 랜덤 코드 표시
- [x] 각 언어당 5개씩 조사
- [x] 관리 모델 구축, 연동

#### song
- Swift 
- JavaScript
- Kotlin
- Ruby
- Php

#### seok
- Python
- C++
- Java
- C
- C#

### 게임 오버 - 캐릭터 대사 표시
- [x] 메시지 담당 모델 구축
- [x] 메시지 표시

**Comment by eeeesong** [comment]
<img width="300" alt="스크린샷 2021-08-13 오후 1 07 39" src="https://user-images.githubusercontent.com/72188416/129303564-6a661058-22bd-499b-b21b-80f46095f5bd.png">

S A B C 등급 없이 대사만 나오니까 뭔가 부족한 감이 없잖아 있어서 
위와 같이 레이아웃을 바꾸고 등급을 추가해볼게요!
이렇게 배치하니까 광고 배너 들어갈 자리도 생기네요
