### ISSUE TITLE
[Refactor] Storage 추상화 개선

### ISSUE THREAD

**Issue by torch-ray** [SinsaStation/FullStackCodingBot#191]

**Comment by eeeesong** [comment]
### 리팩토링 목적
- 데이터 관리 목적을 위해 View Model에서 접근해야 하는 객체가 너무 많다
   - Firebase 담당 객체, 광고 담당 객체, 일반 데이터 객체에 전부 접근하도록 되어 있음
   - 특히, MainViewModel의 Login 처리 및 데이터 로드에서 흐름을 파악하기 어려운 상태.
- 데이터 관리라는 단일 목적에 따라 상위레벨 객체를 통한 추가적인 추상화가 가능해보인다

### 계층도
```
|- View Model
     |--- Storage
          |--- AdStorage
          |--- GameStorage
                |--- CoreDataManager
                |--- FirebaseManager
```

#### * 수정

```
|- View Model
     |--- Storage
          |--- AdStorage
          |--- GameStorage
          |--- BackUpCenter
                |--- CoreDataManager
                |--- FirebaseManager
```

**Comment by eeeesong** [comment]
### PersistenceStorage 기능 분리하기
- 현재 게임 데이터를 제공하는 기능과 데이터를 CoreData에 로드/저장하는 기능이 혼재되어 있음
- 게임 데이터 제공 -> GameStorage
- CoreData CRUD -> CoreDataManager
- 위와 같이 분리 필요
