### ISSUE TITLE
[team] 스토리 

### ISSUE THREAD

**Issue by torch-ray** [SinsaStation/FullStackCodingBot#5]
- 왜 분리하는가에 대한 스토리 고민

**Comment by torch-ray** [comment]
- 풀스택 개발자인  A에게 Mission이 주어짐
- 여러가지 개발 언어를 사용하여 프로젝트를 해야 됨
- 꼰대사장이 내일까지 끝내놓으라고 함
- 눈에서 불나면서 코딩

**Comment by torch-ray** [comment]
- A의 이름은 디버그
- 사장 이름 버그

**Comment by torch-ray** [comment]
디테일 추가: 사장 & 개발자 2인 기업이면 좋겠음 ㅋㅋㅋ

**Comment by torch-ray** [comment]
아니면 개발자제외한 모든 직원은 사장가족? 이것도 나쁘지 않은듯

**Comment by eeeesong** [comment]
가'족'같은 회사 굿
