### ISSUE TITLE
[seok] UI 및 로직

### ISSUE THREAD

**Issue by torch-ray** [SinsaStation/FullStackCodingBot#6]
- UI
- 로직

**Comment by torch-ray** [comment]
1. MainVC
2. RankingVC(이걸 애플겜으로 보여주면 CollectionView인데.. 상의가 필요할듯)
3. 보유 아이템VC(CollectionView)
4. 이벤트/선물 수령VC(Modal)
5. Start버튼 눌렀을 때 InfoVC(Moda)여부 상의필요
6. 실제 게임 돌아가는 VC에 대해서 상의 필요
7. 프로그래밍 언어 로고 IP 문제 -> 확인한바로는 Apple/Swift로고는 리젝가능성 있음
8. 게임이 끝나고 난 후 결과를 보여주는 VC

**Comment by torch-ray** [comment]
화면 구성이 단순하지만 생각보다 많은 ViewController가 필요하며, ViewController간 데이터 전달 코드를 깔끔하게 짜지않으면 유지보수시에 연쇄수정마를 만날 가능성이 높음

**Comment by torch-ray** [comment]
1. 게임시작 -> 10개의 개발 언어 중 랜덤 2개 선택 로직
2. 특정 시간이 지나면 추가적으로 남은 8개 중 1개 랜덤 선택 로직
3. 그리고 일정 시간이 지날 때 마다 몇개를 추가할 것인지 검토 필요
4. 빠른속도로 클리어시 Event모드 돌입(옵셔널 ㅎㅎ)
5. 한번 틀리면 GameOver를 할것인가? 시간을 확 줄일 것인가?
6. 랜덤확률로 특정언어에 gold나 시간증가 같은 item부여

**Comment by torch-ray** [comment]
랜덤 로직 구현을 깔끔하게 해야할듯?

**Comment by eeeesong** [comment]
게임 시작 전에 아이템 설정 창 보여주는거 지금 예시 앱에선 너무 직관적이지 않음
아이템이 굳이 필요한가..? 생각도 

-> 아이템 있거나 한번에 게임오버가 아니면 될 것 같음 (시간 줄이기)

**Comment by eeeesong** [comment]
로고는 직접 그리고
스위프트 -> 드위프트 이런 식으로 한글자만 바꿔서 패러디 어떠신지

**Comment by eeeesong** [comment]
> 스위프트 -> 드위프트 이런 식으로 한글자만 바꿔서 패러디 어떠신지

약간 이런느낌 ㅋㄷ

![패로디](https://user-images.githubusercontent.com/72188416/122750332-53bbad00-d2c9-11eb-9c40-caad91038f14.png)
