### ISSUE TITLE
[song] UI 및 로직

### ISSUE THREAD

**Issue by eeeesong** [SinsaStation/FullStackCodingBot#7]
# 개발 언어 수집형이라고 한다면...
## UI
- 개발 언어들의 레벨을 올릴 관리 공간 필요
- 여러 개발 언어들을 잘 키워내면 시너지가 생겨서 기본 점수 버프를 얻을 수 있음: 버프 모아서 표시하는 UI 필요
  - 예시) swift & kotlin의 레벨이 모두 5이상일경우 `모바일 개발자의 소울` 버프 획득으로 기본 2000점 먹고 시작하기
- 개발 언어는 주인공 개발자의 뇌 속에 자리잡고 있을 것이므로 `뇌` 관리(?)로 이미지화할 수 있음 

## 로직
- 개발 언어 별로 전체 경험치 대비 레벨 표시하기
- 코인 관리 로직 / 구매 & 획득
- 개발 언어 버프 로직들
- 처음부터 모든 개발언어 표시? or 개발 언어도 하나씩 획득 -> 후자일 경우 게임을 잘하면 잘할수록 여러 개발 언어 획득
- 각 개발언어 레벨 당 점수 획득 로직
- 피버타임이 생겨나는 로직 + 피버타임 시 점수 로직

**Comment by eeeesong** [comment]
맞을때마다 개발 언어 한줄

**Comment by eeeesong** [comment]
주기적인 pr 서로 보내기

**Comment by torch-ray** [comment]
매우 좋은생각이군 merge전에는 무조건 상대방 코드 같이 리뷰하기

**Comment by eeeesong** [comment]
`무한의빵집`에서는 메뉴 창 대부분이 모달로 뜨지만 
우리는 아예 TabBar 메뉴를 만들어서 독립된 창으로 띄워주면 어떨까 생각이 있음

예시) 
탭1 - 메인 화면  --> 게임 시작 시 탭바 빼고 full screen으로 덮음
탭2 - 개발 언어 관리 화면 (레벨업 / 버프)
탭3 - 랭킹
탭4 - 설정

코인, 최고 점수 등 주요 정보는 상단 네비게이션 아이템 등으로 모든 탭에서 표시
