### ISSUE TITLE
Unit 복사 현상

### ISSUE THREAD

**Issue by eeeesong** [SinsaStation/FullStackCodingBot#80]
<img src=https://user-images.githubusercontent.com/72188416/126893570-41348725-182b-4fce-a3c2-fdcdcc1722ac.gif width=300>

<img src=https://user-images.githubusercontent.com/72188416/126893412-bddf13ba-2e41-4376-8ca6-9881d95d4f38.PNG width=300>

게임을 하다보면 유닛 셋이 복사되어 있음..

**Comment by torch-ray** [comment]
요고 해결된 거 같음 ~? 몇번 돌려보고 문제 없으면 close해도 될듯

**Comment by eeeesong** [comment]
아직까진 괜찮아 보입니다요
하루만 더 보고 괜춘하면 닫읍시다!

**Comment by eeeesong** [comment]
@torch-ray 저는 이제 문제 없어보임~!
